---
locale: pt
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 13,5%
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 25,0%
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 38,5%
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 75,0%
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Nenhuma das anteriores
  checked: false
name: Previsão do tempo
