---
locale: pt
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: R$ 15
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: R$ 8
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: R$ 32
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: R$ 0
  checked: false
name: Esperança
