---
name: Desafio de Estatística e probabilidades
locale: pt
type: learning
beta: false
teacher_info: ''
language: python3
id_format: "%05d"
order:
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
private: false
