---
locale: pt
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Amplitude
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Desvio absoluto médio
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Variância
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Desvio Padrão
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Todas as anteriores
  checked: true
name: Medidas de dispersão
