---
locale: pt
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 20%
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 26%
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 29%
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 32%
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Nenhuma das anteriores
  checked: false
name: 'Probabilidade: operações com probabilidades'
